[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
name = "badkeys"
version = "0.0.5"
authors = [{name = "Hanno Böck", email = "hanno@hboeck.de"}]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Natural Language :: English",
    "Development Status :: 3 - Alpha",
]
license = {text = "MIT"}
description = "Check cryptographic keys for known weaknesses"
readme = "README.md"
keywords = ["security", "cryptography", "rsa"]
dependencies = [
    "gmpy2",
    "cryptography",
]

[project.urls]
Homepage = "https://badkeys.info/"
"Source Code" = "https://github.com/badkeys/badkeys"
"Bug Tracker" = "https://github.com/badkeys/badkeys/issues"

[project.optional-dependencies]
ssh = ["paramiko"]

[project.scripts]
badkeys = "badkeys.runcli:runcli"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = [
    "badkeys",
    "badkeys.*",
]
namespaces = false
